# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SportsUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(755, 663)
        self.tblLog = QtWidgets.QTableWidget(Dialog)
        self.tblLog.setGeometry(QtCore.QRect(0, 0, 881, 461))
        self.tblLog.setAutoScroll(False)
        self.tblLog.setShowGrid(True)
        self.tblLog.setObjectName("tblLog")
        self.tblLog.setColumnCount(6)
        self.tblLog.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblLog.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLog.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLog.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLog.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLog.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLog.setHorizontalHeaderItem(5, item)
        self.grpAddResult = QtWidgets.QGroupBox(Dialog)
        self.grpAddResult.setGeometry(QtCore.QRect(260, 465, 371, 181))
        self.grpAddResult.setTitle("")
        self.grpAddResult.setObjectName("grpAddResult")
        self.gridLayoutWidget = QtWidgets.QWidget(self.grpAddResult)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(25, 15, 336, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnAddResult = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnAddResult.setObjectName("btnAddResult")
        self.gridLayout.addWidget(self.btnAddResult, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 1)
        self.cmbTeam2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmbTeam2.setObjectName("cmbTeam2")
        self.gridLayout.addWidget(self.cmbTeam2, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 3, 1, 1)
        self.cmbTeam1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmbTeam1.setObjectName("cmbTeam1")
        self.gridLayout.addWidget(self.cmbTeam1, 1, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 4, 1, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 3, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 4, 3, 1, 1)
        self.grpAddTeam = QtWidgets.QGroupBox(Dialog)
        self.grpAddTeam.setGeometry(QtCore.QRect(15, 475, 221, 111))
        self.grpAddTeam.setTitle("")
        self.grpAddTeam.setObjectName("grpAddTeam")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.grpAddTeam)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, -95, 201, 191))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)
        self.btnAddTeam = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnAddTeam.setObjectName("btnAddTeam")
        self.gridLayout_2.addWidget(self.btnAddTeam, 5, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tblLog.setSortingEnabled(True)
        item = self.tblLog.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Team"))
        item = self.tblLog.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "P"))
        item = self.tblLog.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "W"))
        item = self.tblLog.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "D"))
        item = self.tblLog.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "L"))
        item = self.tblLog.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Points"))
        self.btnAddResult.setText(_translate("Dialog", "Add Result"))
        self.label_4.setText(_translate("Dialog", "Team 1 Score"))
        self.label_5.setText(_translate("Dialog", "Team 2 Score"))
        self.label_3.setText(_translate("Dialog", "Team 2"))
        self.label_2.setText(_translate("Dialog", "Team 1"))
        self.btnAddTeam.setText(_translate("Dialog", "Add Team"))
        self.label.setText(_translate("Dialog", "             Team Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
